POST http://localhost:5035/employers
Content-Type: application/json

{
    "Name": "Sage"
}

###
GET http://localhost:5035/employers
###
GET http://localhost:5035/employers/08de2295-ee35-42cf-8a1b-f8709651a5e1
###
DELETE http://localhost:5035/employers/08de2295-ee35-42cf-8a1b-f8709651a5e1
###
PUT http://localhost:5035/employers/08de2295-ee35-42cf-8a1b-f8709651a5e1
Content-Type: application/json

{
    "Name": "SageTwo"
}
